import { appTasks } from '@ohos/hvigor-ohos-plugin';
import fs from 'fs';
import path from 'path';

function parseEnv(content: string): Record<string, string> {
  const map: Record<string, string> = {};
  const lines: string[] = content.split('\n');
  for (const rawLine of lines) {
    const line: string = rawLine.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }
    const eqIndex: number = line.indexOf('=');
    if (eqIndex <= 0) {
      continue;
    }
    const key: string = line.slice(0, eqIndex).trim();
    const value: string = line.slice(eqIndex + 1).trim();
    map[key] = value;
  }
  return map;
}

function syncBackendEnvToEts(): void {
  const projectDir: string = __dirname;
  const envFilePath: string = path.resolve(projectDir, '../../.env');
  const targetFilePath: string = path.resolve(projectDir, 'entry/src/main/ets/common/EnvConfig.ets');

  let backendHost: string = '127.0.0.1';
  let backendPort: string = '8003';

  if (fs.existsSync(envFilePath)) {
    const envContent: string = fs.readFileSync(envFilePath, 'utf8');
    const envMap: Record<string, string> = parseEnv(envContent);
    const hostFromEnv: string | undefined = envMap.BACKEND_HOST;
    const portFromEnv: string | undefined = envMap.BACKEND_HTTP_PORT;
    if (hostFromEnv && hostFromEnv.length > 0) {
      backendHost = hostFromEnv;
    }
    if (portFromEnv && portFromEnv.length > 0) {
      backendPort = portFromEnv;
    }
  }

  const generated: string =
`/**
 * Auto-generated by hvigorfile.ts from project .env
 * Source keys: BACKEND_HOST, BACKEND_HTTP_PORT
 */
export const BACKEND_HOST: string = '${backendHost}';
export const BACKEND_HTTP_PORT: string = '${backendPort}';
`;

  fs.writeFileSync(targetFilePath, generated, { encoding: 'utf8' });
}

syncBackendEnvToEts();

export default {
  system: appTasks,  /* Built-in plugin of Hvigor. It supports the pack project service. */
  plugins:[]         /* Custom plugin to extend the functionality of Hvigor. */
}
